### ISSUE TITLE
Dashboard_CYPWaitsAccess

### ISSUE THREAD

**Issue by alextoddnhs** [nhsengland/MHSDS#5]
Thanks for sharing your SQL code!

Do you have the script that populates NHSE_Sandbox_MentalHealth.dbo.Dashboard_CYPWaitsAccess. I couldn't see it unless I've missed something? I'm trying to recreate the access metric so that I can break it down further (locality, age, ethnicity, etc).

Kind regards, 
Alex

**Comment by CarlMHStats** [comment]
Hi Alex,

I'll get that code added today. The access metric is produced by NHS D and and all our code does is pick up the published values. NHS D made the logic (and code!) available via their meta data file, here: https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/mental-health-services-data-set/statistics-and-reports

This looks at each month individually. If you need a time series I can share some logic that does this in one go.

**Comment by alextoddnhs** [comment]
Hi Carl, 

Thanks for getting back to me, that would be a great help.

**Comment by CarlMHStats** [comment]
closed as complete
